
document.write('<button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"'
        + '><img src="images/icons/icon(1).png" ></button> <button class="btn btn'
        + '-default icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (2).png'
        + '"></button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><'
        + 'img src="images/icons/icon (3).png"></button> <button class="btn btn-d'
        + 'efault icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (4).png">'
        + '</button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><im'
        + 'g src="images/icons/icon (5).png"></button> <button class="btn btn-def'
        + 'ault icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (6).png"></'
        + 'button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img '
        + 'src="images/icons/icon (7).png"></button> <button class="btn btn-defau'
        + 'lt icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (8).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (9).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (10).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (11).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (12).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (13).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (14).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (15).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (16).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (17).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (18).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (19).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (20).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (21).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (22).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (23).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (24).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (25).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (26).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (27).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (28).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (29).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (30).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (31).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (32).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (33).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (34).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (35).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (36).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (37).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (38).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (39).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (40).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (41).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (42).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (43).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (44).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (45).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (46).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (47).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (48).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (49).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (50).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (51).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (52).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (53).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (54).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (55).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (56).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (57).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (58).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (59).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (60).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (61).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (62).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (63).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (64).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (65).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (66).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (67).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (68).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (69).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (70).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (71).png"></button> <button class="btn btn-default'

        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (72).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (73).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (74).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (75).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (76).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (77).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (78).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (79).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (80).png"></but'
        + 'ton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src'
        + '="images/icons/icon (81).png"></button> <button class="btn btn-default'
        + ' icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (82).png"></but'
        + 'ton>  <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (83).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (84).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (85).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (86).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (87).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (88).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (89).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (90).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (91).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (92).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (93).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (94).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (95).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (96).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (97).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (98).png"></bu'
        + 'tton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img sr'
        + 'c="images/icons/icon (99).png"></button> <button class="btn btn-defaul'
        + 't icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (100).png"></b'
        + 'utton> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img s'
        + 'rc="images/icons/icon (101).png"></button> <button class="btn btn-defa'
        + 'ult icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (102).png"><'
        + '/button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img'
        + ' src="images/icons/icon (103).png"></button> <button class="btn btn-de'
        + 'fault icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (104).png"'
        + '></button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><i'
        + 'mg src="images/icons/icon (105).png"></button> <button class="btn btn-'
        + 'default icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (106).pn'
        + 'g"></button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button">'
        + '<img src="images/icons/icon (107).png"></button> <button class="btn bt'
        + 'n-default icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (108).'
        + 'png"></button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="button'
        + '"><img src="images/icons/icon (109).png"></button> <button class="btn '
        + 'btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (110'
        + ').png"></button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="butt'
        + 'on"><img src="images/icons/icon (111).png"></button> <button class="bt'
        + 'n btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon (1'
        + '12).png"></button> <button class="btn btn-default icon-space"  ng-click="GetIcon($event)" type="bu'
        + 'tton"><img src="images/icons/icon (113).png"></button> <button class="'
        + 'btn btn-default icon-space"  ng-click="GetIcon($event)" type="button"><img src="images/icons/icon '
        + '(114).png"></button>');

